---
debian_dev_user: dev
# Public key read from the control node (Mac) and installed for dev:
mac_pubkey_path: "~/.ssh/id_ed25519.pub"

apt_packages:
  - curl
  - gnupg
  - docker.io
  - docker-compose
  - tmux
  - neovim
  - ripgrep
  - wget
  - git
  - htop
  - unzip
  - zip
  - fish
  - golang-go
  - zoxide
  - fzf
  - lazygit
  - build-essential
  - cmake

fish_path: /usr/bin/fish
github_key_comment: debian-dev-vm
node_version: lts-latest
git_user_name: Steffan Karagianis
git_user_email: steffan.karagianis@gmail.com
git_default_branch: main
git_default_editor: nvim
dotfiles_repo: git@github.com:skaragianis/dotfiles.git
